### PR TITLE
probably worth mentioning that photo shows leftovers

### PR DESCRIPTION
**Pull request by dougjohnson**

### CODE REVIEW

**Comment by dougjohnson** [comment]
I'm getting carried away now

**Comment by coldclimate** [comment]
I didn't test that but it looks a bit knackered on my phone

**Comment by dougjohnson** [comment]
Yup - it’s borked! Ooops!

Doug JohnsonChief Technology Officer 
.T  0191 305 1228







        .Alexander House, Cygnet Way, Rainton Bridge, Houghton-le-Spring, DH4 5PH.

**Comment by coldclimate** [comment]
Get it fixed man

**Comment by dougjohnson** [comment]
Errrm... you sure it's not an ops issue? :grinning:

**Comment by coldclimate** [comment]
Yes.

**Comment by dougjohnson** [comment]
Look at my changes, dude!

**Comment by coldclimate** [comment]
Hmm, shall fix after lunch

**Comment by coldclimate** [comment]
My change to blame.  Switching your name to include the @ seemed to derail something but build was successful.  More tests (any test) needed.

**Pull request merged**
